### PR TITLE
Convert to using requests to resolve ssl errors

### PR DESCRIPTION
**Pull request by bdraco**
Fixes https://github.com/home-assistant/core/issues/40072

### CODE REVIEW

**Comment by rfverbruggen** [comment]
@bdraco I've released version 1.0.1 since I made a complete overhaul of Rachiopy.

It's now completely compatible to:

- Python 3 (with Pylint, flake8 and pydocstyle (no exceptions)
- With 100% unittests
- Uses requests instead of httplib2
- Documentation is available (readthedocs)

**Comment by bdraco** [comment]
> 
> If you encounter any problems please contact me so we can work on this together.

Thank you 🚀 

@brg468 is working on the update now (https://github.com/home-assistant/core/issues/40072#issuecomment-703943275)

**Comment by brg468** [comment]
Sorry to bother, but I'm coming across this error and I cant seem to figure out why. 

I get this when running `r.notification.add("MY_DEV_ID","TEST""MY_URL","10")`

`({'date': 'Tue, 06 Oct 2020 15:41:09 GMT', 'content-type': 'application/json;charset=utf-8', 'content-length': '226', 'connection': 'keep-alive', 'server': 'nginx/1.12.1', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': '0', 'x-xss-protection': '1; mode=block', 'x-frame-options': 'DENY', 'x-content-type-options': 'nosniff', 'x-ratelimit-limit': '1700', 'x-ratelimit-remaining': '1584', 'x-ratelimit-reset': '2020-10-07T00:00:00Z', 'status': 500}, {'code': '400', 'error': "Unrecognized token 'device': was expecting ('true', 'false' or 'null')\n at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@1a01b38c; line: 1, column: 8]"})`

Similar error using r.notification.update() except its `"Unrecognized token 'id:'`

Any help would be appreciated!

**Comment by rfverbruggen** [comment]
@brg468 No problem. I did investigate it and it seems that something went wrong since I switched to requests for certain calls.

See: https://github.com/rfverbruggen/rachiopy/commit/7a4dd61e55d9b4dad5ea8815ac6753a9a9aed065

I'll continue testing and let you know when the fix is available in a new version (expect to create this within 24h).

**Comment by brg468** [comment]
> @brg468 No problem. I did investigate it and it seems that something went wrong since I switched to requests for certain calls.
> 
> Could you please create an issue for this problem so we can track the progress in there?
> 
> See: [7a4dd61](https://github.com/rfverbruggen/rachiopy/commit/7a4dd61e55d9b4dad5ea8815ac6753a9a9aed065)
> 
> I'll continue testing and let you know when the fix is available in a new version (expect to create this within 24h).

That changed seemed to fix it for me. 👍

**Pull request merged**
