### PR TITLE
Add timeout to requests

### PR DESCRIPTION
**Pull request by brg468**
It was recommended that we add a timeout to requests.

Does this work? Also I'm guessing you'd want the tests updated, but honestly I don't know much about writing tests..

Let me know what you think. Thanks

### CODE REVIEW

**Review by rfverbruggen — CHANGES_REQUESTED** [review]
I think it would be better if this is a positional argument on the __init__ of RachioObject (e.g. timeout=25) and save it as self.timeout = timeout

And then use it in the self._http_session.request as timeout=self.timeout.

This way everyone that uses RachioPy can decide whether the default timeout is sufficient or whether they would like a different value.

Could you also include the following to the documentation string:
:param timeout: How long to wait for the server to send data before giving up, as a float, or a (connect timeout, read timeout) tuple.
:type timeout: float
:type timeout: tuple

I'll update the tests when the changes are implemented.

**Review by rfverbruggen — COMMENTED** [review]
Thanks @brg468, I'm still deciding on whether the default should be None, since that is the requests default value for timeout. What do you think?

**Comment by brg468** [comment]
> Thanks @brg468, I'm still deciding on whether the default should be None, since that is the requests default value for timeout. What do you think?

I guess I’m alright with it that way since it’s a reasonably long timeout and I wouldn’t think it would cause any issues. But I don’t mind changing it if you’d rather have it None.

**Comment by rfverbruggen** [comment]
> 
> 
> > Thanks @brg468, I'm still deciding on whether the default should be None, since that is the requests default value for timeout. What do you think?
> 
> I guess I’m alright with it that way since it’s a reasonably long timeout and I wouldn’t think it would cause any issues. But I don’t mind changing it if you’d rather have it None.

Fair enough, we will leave it to a default value of 25. Thanks!

**Review by rfverbruggen — APPROVED** [review]

**Comment by rfverbruggen** [comment]
@brg468 Thanks for your effort. 1.0.3 is released to pypi which includes the timeout. Good luck implementing this change in home-assistant.

**Comment by brg468** [comment]
Thanks for your help as well! 

BTW I believe I noticed 1 small error in the docs. getInfo() is outdated. Can submit a PR to fix or leave it up to you.

```
Getting Started
from rachiopy import Rachio

r = Rachio("8e600a4c-0027-4a9a-9bda-dc8d5c90350d")
resp, content = r.person.getInfo()

print (resp["status"])
print (content["id"])
```

**Comment by rfverbruggen** [comment]
I'll fix it, need to improve the tests too (including python 3.9). But wanted to help you implementing it in home-assistant.

Functionality is more important than tests and documentation. I added both of them more as a learning project for myself!

**Pull request merged**
